spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: 

# The SQL dialectmakes Hibernate generate better SQL for the chosen database
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# JPA Settings
  jpa.hibernate.ddl_auto: create
  spring.jpa.database: mysql
